import { useQuery } from "@tanstack/react-query";
import { Link, useLocation } from "wouter";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Building, Tags, Users, BarChart3, RefreshCw, FileText, Plus, UserPlus, Table, TrendingUp, ArrowUp, AlertTriangle } from "lucide-react";
import { SyncButton } from "@/components/sync-button";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import { type Vendor, type Representative, type Category } from "@shared/schema";

export default function Dashboard() {
  const [, setLocation] = useLocation();
  
  const { data: vendors, isLoading: vendorsLoading } = useQuery<Vendor[]>({
    queryKey: ["/api/vendors"],
  });

  const { data: representatives, isLoading: repsLoading } = useQuery<Representative[]>({
    queryKey: ["/api/representatives"],
  });

  const { data: categories, isLoading: categoriesLoading } = useQuery<Category[]>({
    queryKey: ["/api/categories"],
  });

  const isLoading = vendorsLoading || repsLoading || categoriesLoading;

  const metrics = {
    totalVendors: vendors?.length || 0,
    totalCategories: categories?.length || 0,
    totalReps: representatives?.length || 0,
    avgVendorsPerCategory: categories?.length ? ((vendors?.length || 0) / categories.length).toFixed(1) : "0.0",
  };

  const getChartColor = (categoryName: string) => {
    const colors = {
      'concrete': '#3b82f6',
      'decking': '#10b981', 
      'electrical': '#f59e0b',
      'fence': '#8b5cf6',
      'hardware': '#6b7280',
      'lumber': '#d97706',
      'roofing': '#dc2626',
      'windows': '#0891b2',
      'default': '#6366f1'
    };
    const key = categoryName.toLowerCase();
    return colors[key as keyof typeof colors] || colors.default;
  };

  // Generate chart data
  const chartData = categories?.map(category => {
    const vendorsInCategory = vendors?.filter(vendor => 
      vendor.categories?.some(cat => cat.toLowerCase().includes(category.name.toLowerCase()))
    ).length || 0;
    
    return {
      name: category.name,
      vendors: vendorsInCategory,
      fill: getChartColor(category.name)
    };
  }).sort((a, b) => b.vendors - a.vendors) || [];

  const recentActivity = [
    {
      type: "success",
      icon: Plus,
      title: "New vendor added",
      description: "ABC Supply Co - 2 hours ago",
    },
    {
      type: "info",
      icon: UserPlus,
      title: "Vendor updated",
      description: "Beacon materials - 5 hours ago",
    },
    {
      type: "warning",
      icon: Tags,
      title: "Category restructured",
      description: "Roofing subcategories - 1 day ago",
    },
  ];

  const generateDashboardReport = () => {
    const reportData = {
      title: "LowesPro Dashboard Report",
      generatedAt: new Date().toLocaleDateString(),
      metrics,
      vendors: vendors?.slice(0, 10) || [],
      categories: categories?.slice(0, 10) || [],
    };

    const reportContent = `
LowesPro Dashboard Report
Generated: ${reportData.generatedAt}

SUMMARY METRICS
================
Total Vendors: ${reportData.metrics.totalVendors}
Total Categories: ${reportData.metrics.totalCategories}
Total Sales Representatives: ${reportData.metrics.totalReps}
Average Vendors per Category: ${reportData.metrics.avgVendorsPerCategory}

RECENT VENDORS
===============
${reportData.vendors.map(v => `• ${v.companyName} (${v.vendorNumber}) - ${v.categories?.join(', ') || 'No categories'}`).join('\n')}

CATEGORIES
===========
${reportData.categories.map(c => `• ${c.name} (Level ${c.level}) - ${c.vendorCount} vendors`).join('\n')}

Report generated by LowesPro Vendor Management System
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `lowespro-dashboard-report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return (
      <div className="flex-1 p-6 space-y-6">
        <div className="animate-pulse space-y-6">
          <div className="h-8 bg-gray-200 rounded w-1/4"></div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {[...Array(4)].map((_, i) => (
              <div key={i} className="h-32 bg-gray-200 rounded-xl"></div>
            ))}
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="flex-1 p-4 sm:p-6 space-y-4 sm:space-y-6">
      {/* Header */}
      <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between space-y-4 lg:space-y-0">
        <div>
          <h1 className="text-2xl sm:text-3xl font-bold text-gray-900">Dashboard</h1>
          <p className="text-gray-600 mt-1 text-sm sm:text-base">Overview of your vendor management system</p>
        </div>
        <div className="flex flex-col sm:flex-row space-y-2 sm:space-y-0 sm:space-x-3 w-full lg:w-auto">
          <SyncButton />
          <Button variant="outline" className="font-medium w-full sm:w-auto">
            <RefreshCw className="mr-2 h-4 w-4" />
            Refresh
          </Button>
          <Button className="bg-blue-600 hover:bg-blue-700 font-medium w-full sm:w-auto" onClick={generateDashboardReport}>
            <FileText className="mr-2 h-4 w-4" />
            Generate Report
          </Button>
        </div>
      </div>

      {/* Metrics Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-6">
        {/* Total Vendors Card */}
        <Card 
          className="construction-shadow cursor-pointer hover:shadow-lg transition-shadow"
          onClick={() => setLocation('/vendors')}
        >
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Total Vendors</p>
                <p className="text-3xl font-bold text-gray-900 mt-2">{metrics.totalVendors}</p>
                <p className="text-sm text-green-600 mt-1 flex items-center">
                  <ArrowUp className="h-3 w-3 mr-1" />
                  <span>12% from last month</span>
                </p>
              </div>
              <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
                <Building className="text-blue-600 h-6 w-6" />
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Categories Card */}
        <Link href="/categories">
          <Card className="construction-shadow cursor-pointer hover:shadow-lg transition-shadow">
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-gray-600">Categories</p>
                  <p className="text-3xl font-bold text-gray-900 mt-2">{metrics.totalCategories}</p>
                  <p className="text-sm text-gray-500 mt-1">
                    <span>Across all materials</span>
                  </p>
                </div>
                <div className="w-12 h-12 bg-orange-100 rounded-lg flex items-center justify-center">
                  <Tags className="text-orange-600 h-6 w-6" />
                </div>
              </div>
            </CardContent>
          </Card>
        </Link>

        {/* Sales Reps Card */}
        <Card 
          className="construction-shadow cursor-pointer hover:shadow-lg transition-shadow"
          onClick={() => setLocation('/representatives')}
        >
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Sales Representatives</p>
                <p className="text-3xl font-bold text-gray-900 mt-2">{metrics.totalReps}</p>
                <p className="text-sm text-orange-600 mt-1 flex items-center">
                  <AlertTriangle className="h-3 w-3 mr-1" />
                  <span>Needs attention</span>
                </p>
              </div>
              <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
                <Users className="text-blue-600 h-6 w-6" />
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Avg Vendors/Category Card */}
        <Card 
          className="construction-shadow cursor-pointer hover:shadow-lg transition-shadow"
          onClick={() => setLocation('/categories')}
        >
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Avg Vendors/Category</p>
                <p className="text-3xl font-bold text-gray-900 mt-2">{metrics.avgVendorsPerCategory}</p>
                <p className="text-sm text-gray-500 mt-1">
                  <span>Good distribution</span>
                </p>
              </div>
              <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center">
                <BarChart3 className="text-green-600 h-6 w-6" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Charts Section */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Vendors by Category Chart */}
        <Card className="lg:col-span-2 construction-shadow">
          <CardContent className="p-6">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-lg font-semibold text-gray-900">Vendors by Category</h3>
              <Button variant="ghost" className="text-sm text-blue-600 hover:text-blue-700 font-medium">
                View Details
              </Button>
            </div>
            <div className="h-64">
              {chartData.length > 0 ? (
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={chartData} margin={{ top: 20, right: 30, left: 20, bottom: 5 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
                    <XAxis 
                      dataKey="name" 
                      stroke="#64748b" 
                      fontSize={12}
                      angle={-45}
                      textAnchor="end"
                      height={80}
                    />
                    <YAxis stroke="#64748b" fontSize={12} />
                    <Tooltip 
                      formatter={(value, name) => [value, 'Vendors']}
                      labelFormatter={(label) => `Category: ${label}`}
                      contentStyle={{
                        backgroundColor: '#fff',
                        border: '1px solid #e2e8f0',
                        borderRadius: '8px',
                        boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)'
                      }}
                    />
                    <Bar dataKey="vendors" radius={[4, 4, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              ) : (
                <div className="h-full bg-gradient-to-r from-blue-50 to-orange-50 rounded-lg flex items-center justify-center">
                  <div className="text-center">
                    <BarChart3 className="h-16 w-16 text-gray-400 mx-auto mb-4" />
                    <p className="text-gray-500 font-medium">No Data Available</p>
                    <p className="text-sm text-gray-400">Add vendors and categories to see chart</p>
                  </div>
                </div>
              )}
            </div>
          </CardContent>
        </Card>

        {/* Recent Activity */}
        <Card className="construction-shadow">
          <CardContent className="p-6">
            <h3 className="text-lg font-semibold text-gray-900 mb-6">Recent Activity</h3>
            <div className="space-y-4">
              {recentActivity.map((activity, index) => {
                const Icon = activity.icon;
                const colorClasses = {
                  success: "bg-green-100 text-green-600",
                  info: "bg-blue-100 text-blue-600",
                  warning: "bg-orange-100 text-orange-600",
                };
                
                return (
                  <div key={index} className="flex items-start space-x-3">
                    <div className={`w-8 h-8 rounded-full flex items-center justify-center ${colorClasses[activity.type as keyof typeof colorClasses]}`}>
                      <Icon className="h-4 w-4" />
                    </div>
                    <div className="flex-1">
                      <p className="text-sm font-medium text-gray-900">{activity.title}</p>
                      <p className="text-xs text-gray-500">{activity.description}</p>
                    </div>
                  </div>
                );
              })}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Quick Actions */}
      <Card className="construction-shadow">
        <CardContent className="p-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-6">Quick Actions</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Link href="/vendors">
              <Button 
                variant="outline" 
                className="p-6 h-auto border-2 border-dashed border-gray-300 hover:border-blue-600 hover:bg-blue-50 transition-colors group"
              >
                <div className="text-center">
                  <Plus className="h-8 w-8 text-gray-400 group-hover:text-blue-600 mx-auto mb-2" />
                  <p className="font-medium text-gray-700 group-hover:text-blue-600">Add New Vendor</p>
                  <p className="text-sm text-gray-500">Register a new supplier</p>
                </div>
              </Button>
            </Link>
            
            <Link href="/representatives">
              <Button 
                variant="outline" 
                className="p-6 h-auto border-2 border-dashed border-gray-300 hover:border-blue-600 hover:bg-blue-50 transition-colors group"
              >
                <div className="text-center">
                  <UserPlus className="h-8 w-8 text-gray-400 group-hover:text-blue-600 mx-auto mb-2" />
                  <p className="font-medium text-gray-700 group-hover:text-blue-600">Add Sales Rep</p>
                  <p className="text-sm text-gray-500">Create rep contact</p>
                </div>
              </Button>
            </Link>
            
            <Link href="/categories">
              <Button 
                variant="outline" 
                className="p-6 h-auto border-2 border-dashed border-gray-300 hover:border-blue-600 hover:bg-blue-50 transition-colors group"
              >
                <div className="text-center">
                  <Table className="h-8 w-8 text-gray-400 group-hover:text-blue-600 mx-auto mb-2" />
                  <p className="font-medium text-gray-700 group-hover:text-blue-600">Manage Categories</p>
                  <p className="text-sm text-gray-500">Organize materials</p>
                </div>
              </Button>
            </Link>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
